// <auto-generated />
using System;
using Jey.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jey.Infrastructure.Migrations
{
    [DbContext(typeof(JeyContext))]
    partial class JeyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Jey.Domain.Models.Announcements", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnnouncementName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AnnouncementValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnnouncementsQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentType")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserIdAnnouncement")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("UserIdAnnouncement");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Jey.Domain.Models.Guild", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("OwnerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Jey.Domain.Models.Item", b =>
                {
                    b.Property<string>("ItemKeyOrLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Jcoin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scoin")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemKeyOrLink");

                    b.ToTable("items");
                });

            modelBuilder.Entity("Jey.Domain.Models.SalesHistory", b =>
                {
                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date_sale")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemKeyOrLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SellTo")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ItemKeyOrLink");

                    b.HasIndex("SellTo");

                    b.ToTable("SalesHistory");
                });

            modelBuilder.Entity("Jey.Domain.Models.User", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Jcoin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Scoin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Jey.Domain.Models.Announcements", b =>
                {
                    b.HasOne("Jey.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIdAnnouncement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jey.Domain.Models.SalesHistory", b =>
                {
                    b.HasOne("Jey.Domain.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemKeyOrLink")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jey.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("SellTo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
